// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-2-WEO7VUDy4tUhtlWwpyPecjM-QJv_I',
    appId: '1:1027509621082:web:e182ca02644cf12c246363',
    messagingSenderId: '1027509621082',
    projectId: 'smarttraveler-58384',
    authDomain: 'smarttraveler-58384.firebaseapp.com',
    storageBucket: 'smarttraveler-58384.firebasestorage.app',
    measurementId: 'G-4S9T036RNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb9UfMetoE63zrOdpZQuUZldTnnxeHk9A',
    appId: '1:1027509621082:android:ec95317e25293b87246363',
    messagingSenderId: '1027509621082',
    projectId: 'smarttraveler-58384',
    storageBucket: 'smarttraveler-58384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzw4mxkERQIic5mIwpxAFc0la_kV874bc',
    appId: '1:1027509621082:ios:9cd53a2c933a6957246363',
    messagingSenderId: '1027509621082',
    projectId: 'smarttraveler-58384',
    storageBucket: 'smarttraveler-58384.firebasestorage.app',
    androidClientId: '1027509621082-kkq9889c2gbdebkgkfdebibp5ptssiut.apps.googleusercontent.com',
    iosClientId: '1027509621082-fcabgm28q5i0rijf5i28om34t3646j6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTraveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzw4mxkERQIic5mIwpxAFc0la_kV874bc',
    appId: '1:1027509621082:ios:9cd53a2c933a6957246363',
    messagingSenderId: '1027509621082',
    projectId: 'smarttraveler-58384',
    storageBucket: 'smarttraveler-58384.firebasestorage.app',
    androidClientId: '1027509621082-kkq9889c2gbdebkgkfdebibp5ptssiut.apps.googleusercontent.com',
    iosClientId: '1027509621082-fcabgm28q5i0rijf5i28om34t3646j6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTraveler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-2-WEO7VUDy4tUhtlWwpyPecjM-QJv_I',
    appId: '1:1027509621082:web:885574486b56bacb246363',
    messagingSenderId: '1027509621082',
    projectId: 'smarttraveler-58384',
    authDomain: 'smarttraveler-58384.firebaseapp.com',
    storageBucket: 'smarttraveler-58384.firebasestorage.app',
    measurementId: 'G-8PDLSR950N',
  );

}